# Generated by Django 5.2.2 on 2025-06-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField()),
                ('images', models.ImageField(blank=True, null=True, upload_to='news')),
                ('created_time_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
