# Generated by Django 5.2.2 on 2025-07-03 13:05

import O_H_SHOKUBI.models
import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_for_url', models.SlugField(blank=True, max_length=200)),
                ('title', models.CharField(max_length=100)),
                ('photo', O_H_SHOKUBI.models.CloudinaryImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='lawyers/')),
                ('bio', models.TextField(blank=True)),
                ('education', models.TextField(blank=True)),
                ('practice_area', models.CharField(blank=True, max_length=200)),
                ('linkedin', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255)),
                ('headline_for_url', models.SlugField(blank=True, max_length=255)),
                ('news_images', O_H_SHOKUBI.models.CloudinaryImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='news/')),
                ('news_body', models.TextField(blank=True)),
                ('created_time_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice_name', models.CharField(max_length=200)),
                ('practice_name_for_url', models.SlugField(blank=True, max_length=200)),
                ('practice_info', models.TextField(blank=True)),
                ('practice_image', models.ImageField(blank=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='practice/')),
                ('practice_expertise_raw', models.TextField(blank=True, help_text='Separate each item with a new line')),
                ('lawyers', models.ManyToManyField(blank=True, to='O_H_SHOKUBI.lawyer')),
            ],
            options={
                'verbose_name': 'Practice',
                'verbose_name_plural': 'Practices',
            },
        ),
    ]
