# Generated by Django 5.2.2 on 2025-07-02 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('O_H_SHOKUBI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_for_url', models.SlugField(blank=True, max_length=200)),
                ('title', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='lawyers/')),
                ('bio', models.TextField(blank=True)),
                ('education', models.TextField(blank=True)),
                ('practice_area', models.CharField(blank=True, max_length=200)),
                ('linkedin', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='news',
            name='images',
        ),
        migrations.AddField(
            model_name='news',
            name='headline_for_url',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='news',
            name='news_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='news',
            name='news_images',
            field=models.ImageField(blank=True, null=True, upload_to='news/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='headline',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice_name', models.CharField(max_length=200)),
                ('practice_name_for_url', models.SlugField(blank=True, max_length=200)),
                ('practice_info', models.TextField(blank=True)),
                ('practice_image', models.ImageField(blank=True, upload_to='practice/')),
                ('practice_expertise_raw', models.TextField(blank=True, help_text='Separate each item with a new line')),
                ('lawyers', models.ManyToManyField(blank=True, to='O_H_SHOKUBI.lawyer')),
            ],
            options={
                'verbose_name': 'Practice',
                'verbose_name_plural': 'Practices',
            },
        ),
    ]
