# Generated by Django 5.2.2 on 2025-06-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('O_H_SHOKUBI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_body',
            field=models.TextField(blank=True),
        ),
    ]
