# Generated by Django 5.2.2 on 2025-06-18 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('O_H_SHOKUBI', '0002_news_news_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='images',
            new_name='news_images',
        ),
    ]
