# Generated by Django 5.2.2 on 2025-07-02 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('O_H_SHOKUBI', '0002_lawyer_remove_news_images_news_headline_for_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='practice_image',
            field=models.ImageField(upload_to='practice/'),
        ),
    ]
