# Generated by Django 5.2.2 on 2025-06-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('O_H_SHOKUBI', '0003_rename_images_news_news_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_images',
            field=models.ImageField(blank=True, null=True, upload_to='news/'),
        ),
    ]
