# Generated by Django 5.2.2 on 2025-07-02 21:58

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('O_H_SHOKUBI', '0003_alter_practice_practice_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='practice_image',
            field=models.ImageField(blank=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='practice/'),
        ),
    ]
