# Generated by Django 5.2.2 on 2025-07-02 22:09

import O_H_SHOKUBI.models
import cloudinary_storage.storage
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('O_H_SHOKUBI', '0004_alter_practice_practice_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer',
            name='photo',
            field=O_H_SHOKUBI.models.CloudinaryImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='lawyers/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_images',
            field=O_H_SHOKUBI.models.CloudinaryImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='news/'),
        ),
    ]
