# Generated by Django 5.2.2 on 2025-06-19 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('O_H_SHOKUBI', '0004_alter_news_news_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='headline_for_url',
            field=models.CharField(blank=True),
        ),
    ]
