# Generated by Django 5.2.2 on 2025-06-19 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('O_H_SHOKUBI', '0005_news_headline_for_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='headline',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='news',
            name='headline_for_url',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
