# Generated by Django 5.2.2 on 2025-06-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('O_H_SHOKUBI', '0006_alter_news_headline_alter_news_headline_for_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='lawyers/')),
                ('bio', models.TextField(blank=True)),
                ('education', models.TextField(blank=True)),
                ('specialization', models.CharField(blank=True, max_length=200)),
                ('linkedin', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
    ]
