# Generated by Django 5.2.2 on 2025-06-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('O_H_SHOKUBI', '0007_lawyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='name_for_url',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
