# Generated by Django 5.1.3 on 2025-06-26 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('O_H_SHOKUBI', '0008_lawyer_name_for_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lawyer',
            old_name='specialization',
            new_name='practice',
        ),
    ]
