# Generated by Django 5.1.3 on 2025-06-26 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('O_H_SHOKUBI', '0009_rename_specialization_lawyer_practice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lawyer',
            old_name='practice',
            new_name='practice_area',
        ),
    ]
