# Generated by Django 5.1.3 on 2025-06-26 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('O_H_SHOKUBI', '0010_rename_practice_lawyer_practice_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice_name', models.CharField(max_length=200)),
                ('practice_name_for_url', models.SlugField(blank=True, max_length=200)),
                ('practice_info', models.TextField(blank=True)),
                ('lawyers', models.ManyToManyField(blank=True, to='O_H_SHOKUBI.lawyer')),
            ],
            options={
                'verbose_name': 'Practice',
                'verbose_name_plural': 'Practices',
            },
        ),
    ]
