# Generated by Django 5.1.3 on 2025-06-26 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('O_H_SHOKUBI', '0011_practice'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='practice_image',
            field=models.ImageField(blank=True, upload_to='practice/'),
        ),
    ]
