# Generated by Django 5.1.3 on 2025-06-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('O_H_SHOKUBI', '0012_practice_practice_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='practice_expertise_raw',
            field=models.TextField(blank=True, help_text='Separate each item with a new line'),
        ),
    ]
